language: php

sudo: false

env:
  global:
    - COMPOSER_NO_INTERACTION="1"

php:
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - mysql

install:
  - composer install

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('test') WHERE user='travis';\nFLUSH PRIVILEGES;\nCREATE DATABASE IF NOT EXISTS test;\n" | mysql -u root
